name: Coding Standards
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  verify-code-meets-standards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Configure Poetry
        run: poetry install

      - name: isort
        run: poetry run isort -c .

      - name: flake8
        run: poetry run flake8 .

      - name: mypy
        run: poetry run mypy .

      - name: black
        run: poetry run black .

      - name: pytest
        run: poetry run pytest tests/
